youths/schema/mutations.py, youths/schema/queries.py, youths/schema/types.py, youths/tests/test_graphql_api_additional_contact_persons.py, youths/tests/test_graphql_federation.py, youths/tests/test_graphql_mutations.py, youths/tests/test_graphql_queries.py
This PR refactors the youth profile GQL API to have `ProfileNode` and `YouthProfileNode` types instead of just the former. 
`ProfileNode` extends the `ProfileNode` in open-city-profile by adding just one non-required extra field for youth profile. This will allow the `YouthProfileNode` type itself to have fields that are required. There would've been some federation related issues if the fields in `YouthProfileNode` would've been added straight to the `ProfileNode` type.
All normal queries and mutations in the GQL API return `YouthProfileNode` objects. Extended `ProfileNode` is there only for allowing the API to federated Apollo federation gateway.
=> YM-277 | Refactor GQL API to have a separate YouthProfileNode type

common_utils/profile.py, common_utils/tests/conftest.py, common_utils/tests/responses/my_profile_response.json, common_utils/tests/responses/profile_access_token_response.json, common_utils/tests/test_profile_gql_queries.py, youths/models.py, youths/notifications.py, youths/schema/mutations.py, youths/tests/conftest.py, youths/tests/factories.py, youths/tests/test_graphql_api_additional_contact_persons.py, youths/tests/test_graphql_mutations.py, youths/utils.py
Additional information (like youth's name and email) is fetched from Helsinki profile backend for youth membership approval and confirmation messages using either the Helsinki profile API token provided during a mutation call or using the temporary access token saved into to youth profile.
* `approveYouthPprofile` mutations will respond with `TOKEN_EXPIRED_ERROR` if the temporary access token for Helsinki profile is considered expired (or it's not stored in the backend) in which case the approval notification should be regenerated with `renewMyYouthProfile`
=> YM-417 YM-418 | Fetch additional information for youth membership approval and confirmation messages

.prod/on_deploy.sh, docker-entrypoint.sh, requirements.in, requirements.txt, youth_membership/settings.py
This PR should remove will remove django-reversion related DB tables from QA which cause `IntegrityError` errors.
Refs YM-388
P.S. This code will be reverted once the reversion migrations have been reversed in QA.
=> YM-388 | Remove django-reversion DB table from QA

youths/management/commands/import_youth_data.py
Added management command `import_youth_data` which takes a JSON created by the open-city-profile backend's [`export_youth_data`](https://github.com/City-of-Helsinki/open-city-profile/pull/230) command, and creates `YouthProfile`s, `AdditionalContactPerson`s, `User`s and `ADGroup`s
based on that file. The script also creates the admin group for youth admins, and mappings from it the `ADGroup`s.
When run, at first all existing non-admin users, `YouthProfile`s and `ADGroup`s are deleted. The script is meant to be executed only one time to migrate data from open-city-profile to youth-membership.
=> YM-296 | Add management command for importing youth data

.gitlab-ci.yml
This PR ensures CSRF and session cookies will only be sent through HTTPS. Also remove the commented configuration which would've been needed for serving the API from a subfolder of api.hel.fi.
Refs YM-424
=> YM-424 | Ensure session and CSRF cookies are only sent with HTTPS

.gitlab-ci.yml
This PR adds a missing OIDC client secret into the CI review environments.
=> YM-424 | Add OIDC client secret into CI review env

common_utils/views/gdpr.py, requirements-dev.in, requirements-dev.txt, youths/tests/test_gdpr_api.py
This PR adds logic which also removes the related `User` model instance when a `YouthProfile` instance is removed using the GDPR API. Also a small extra check to the GDPR API permissions is added to make sure only youth profiles with a user connection can be accessed.
Development requirement package versions are constrained by the package versions in `requirements.txt`.
=> Remove the user related to the youth profile deleted using the GDPR API

youths/management/commands/import_youth_data.py
Youth profile approval in the new updated flow requires a temporary approval token to be in place at Helsinki profile backend. Since it will not be, the `approval_token` should be cleared in import.
Refs YM-296
=> Unset YouthProfile.approval_token on data import

users/admin.py, youths/admin.py
This PR adds a link to a related YouthProfile object in UserAdmin. UserAdmin (in Django admin) is modified to include a link to a related youth profile object in similar way as what has been done in open-city-profile.
=> Include YouthProfile link in UserAdmin

youths/models.py, youths/schema/types.py, youths/tests/test_graphql_mutations.py, youths/tests/test_graphql_queries.py, youths/tests/test_models.py
This PR simplifies the logic for determining the membership status of a youth profile. It should also fix few cases which were missed e.g. regarding profiles with RENEWING status.
Status will be determined in this order:
1. if expiration < today => expired
2. if profile hasn't been approved by a guardian => PENDING
3. if expiration > calculated expiration based on approval time => RENEWING
4. Profile is ACTIVE if none of the previous statements were true.
The PR also refactors the renewable logic a bit. A youth profile is considered to be renewable always when the status is `EXPIRED`. Also the profile can be renewed if the profile has been approved at least once and the current expiration date differs from the calculated expiration date. On most cases this means that even an ACTIVE …
=> YM-463 | Fix membership status logic

youths/models.py, youths/tests/test_graphql_mutations.py, youths/tests/test_models.py
While a youth profile is being renewed and it's still waiting for an approval from a guardian, the RENEWING status is returned
for a profile which is still active while the renewal is ongoing. PENDING will be returned for an expired youth profile, which is waiting for the approval from a guardian.
Different status now are:
- ACTIVE = membership is active
- PENDING = membership is waiting for approval and is either inactive or expired
- RENEWING = membership is active, but renewal is waiting for approval
- EXPIRED = membership has expired
Refs YM-463, YM-469
=> YM-463 YM-469 | Fine tune YouthProfile RENEWING membership status logic

.prod/uwsgi.ini
This PR stops uWSGI from logging requests for /healthz and /readiness endoints.
=> YM-465 | Stop logging requests for /healthz and /readiness endoints

youths/enums.py
[YM-480](https://helsinkisolutionoffice.atlassian.net/browse/YM-480) assumes that the supported languages includes French. In order to allow users to set their "language at home" value to French, we extend the YouthLangauge enum to include it.
@charn Please advise if I've overlooked something.
=> YM-500 | Add French to YouthLanguage

youth_membership/settings.py
Adds additional languages (French, Russian, Somali, Arabic, Estonian) into language configurations so that email notifications can be translated into these languages.
=> YM-501 | Use additional language in PR and staging environments

youth_membership/settings.py
This PR syncs the notification templates which are created for a new backend instances with the current production versions. The templates now include language specific URLs.
Also `django-parler` caching is disabled since Django's default `LocMemCache` can cause display issues e.g. when updating the template translations and the service is run on more than one process (which happens on our production and staging environments).
=> Notification template updates

youths/models.py, youths/schema/mutations.py, youths/tests/test_graphql_mutations.py
Provides the Jassari service url directly when invoking `send_notification` to fix crash caused by missing context value.
=> FIX YM-479 | Provide base url value directly

common_utils/tests/snapshots/snap_test_commands.py, templates/jinja2/email/base_generic.html, templates/jinja2/email/macros.jinja, templates/jinja2/email/messages/youth_profile_confirmation_needed_en.html, templates/jinja2/email/messages/youth_profile_confirmation_needed_fi.html, templates/jinja2/email/messages/youth_profile_confirmation_needed_sv.html, templates/jinja2/email/messages/youth_profile_confirmed_en.html, templates/jinja2/email/messages/youth_profile_confirmed_fi.html, templates/jinja2/email/messages/youth_profile_confirmed_sv.html
These changes fix the way in which line breaks are declared in some of the templates. The old syntax is not valid HTML, but gets parsed by browsers and some email clients due to some quirk in the rendering logic.
The changes also alter the way in which the the CTA link is styled to appear like a button. Desktop Outlook poorly supported the previous approach.
=> Fix styling issues in some email clients

youths/tests/test_gdpr_api.py
The failing test wasn't controlling the time. Test failed because it was expecting a different expiration date i.e. test was expecting a date relative to the time when the test was originally written.
=> Fix a broken test due to not considering the passage of time

.github/workflows/staging.yml
This PR adds `workflow_dispatch` trigger. With this in place it's possible to manually run staging workflow from Actions - tab.
=> Chore | Add possibility to manually trigger staging workflow.

common_utils/views/graphql.py, youths/tests/test_graphql_mutations.py
DEVOPS-490. A year has passed and the youth profile used in a test was not a youth anymore. Fixed by freezing the time to last year.
=> Fix youth profile creation test
